### ISSUE TITLE
readODS::read_ods eating up spaces

### ISSUE THREAD

**Issue by ramiromagno** [chainsawriot/readODS#74] opened 2021-08-09 08:12 UTC
This bug took me a while to realise...

My readODS version is 1.7.0.

So it seems that `readODS::read_ods()` is converting several spaces into one.

``` r
readODS::read_ods('~/dwl/ab.ods')
#>   n_spaces example
#> 1        1     A B
#> 2        2     A B
#> 3        3     A B
#> 4        4     A B
#> 5        5     A B
```

This is how the input file looks like:

![snap](https://user-images.githubusercontent.com/19862384/128676807-93da0708-7aed-4916-b7b3-1d454a1161d2.png)

[ab.ods](https://github.com/chainsawriot/readODS/files/6952902/ab.ods)

**Comment by steffen-stell** [comment] 2021-08-22 19:59
I can confirm this issue. While it may even be desirable default behavior, there needs to be an argument to prevent it for the rare case where multiple spaces are meaningful.

**Comment by chainsawriot** [comment] 2021-11-27 14:41
I think I found the problem. The problem is that the current implementation can't handle <text:s> from OASIS 1.2

http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part1.html#__RefHeading__1415202_253892949

A fix is in the making.

**Closed** 2021-11-27 16:33 UTC
Labels: bug
